apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: cdxker-keycloak
  namespace: keycloak
spec:
  instances: 1
  # bootstrapAdmin:
  #   user:
  #     secret: "trieve-keycloak-admin-override"
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      memory: 1Gi
  db:
    vendor: postgres
    host: keycloak-postgres-rw
    database: app
    usernameSecret:
      name: keycloak-postgres-app
      key: username
    passwordSecret:
      name: keycloak-postgres-app
      key: password
  http:
    httpEnabled: true
  ingress:
    enabled: false
  hostname:
    strict: false
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
