apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  instances: 1
  storage:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      memory: 2Gi
