# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-images
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 40Gi
