apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    chart: headlamp
    repoURL: https://headlamp-k8s.github.io/headlamp
    targetRevision: "*"  # or specify a specific chart version
    helm:
      releaseName: headlamp
      valuesObject: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
